---
vm_user: "AzureUser"
web_user: "AzureUser"
paquetes_requeridos_vm:
  - 'firewalld'
  - 'podman'
  - 'openssl'
  - 'python3-apt'
  - 'python3-passlib'
  - 'apache2'

webcred_user: "operator"
webcred_passwd: ".htpasswd"

ssl_key: "OnlyMe.key"
ssl_cert: "OnlyMe.crt"
ssl_csr: "OnlyMe.csr"
ssl_country_name: "ES"
ssl_org_name: "UNIR"
ssl_org_unit: "DevOpsCloud"
ssl_common_name: "OnlyMe"
ssl_email_address: "borja.rodriguezlopezd077@comunidadunir.net"

webapp_dir: "/home/{{ web_user }}/webapp"
