---
vm_user: "AzureUser"
packages_apt:
  - 'firewalld'
  - 'podman'
  - 'openssl'
  - 'python3-apt'
  - 'python3-passlib'
  - 'python3-pip'

packages_pip:
  - 'kubernetes>=12.0.0'

base_conf_dir: "/home/{{ web_user }}/web_config"
html_dir: "{{ base_conf_dir }}/html"
conf_dirs:
  - "{{ html_dir }}"
