---
vm_user: "AzureUser"
web_user: "AzureUser"
paquetes_requeridos_vm:
  - 'firewalld'
  - 'podman'
  - 'openssl'
  - 'python3-apt'
  - 'python3-passlib'
  - 'apache2'

webcred_user: "operator"
webcred_passwd: ".htpasswd"

ssl_key: "OnlyMe.key"
ssl_cert: "OnlyMe.crt"
ssl_csr: "OnlyMe.csr"
ssl_country_name: "ES"
ssl_org_name: "UNIR"
ssl_org_unit: "DevOpsCloud"
ssl_common_name: "OnlyMe"
ssl_email_address: "borja.rodriguezlopezd077@comunidadunir.net"

webapp_dir: "/home/{{ web_user }}/webapp"
dest_ssl_key_dir: "/etc/ssl/certs"
dest_ssl_private_dir: "/etc/ssl/private"
dest_sites_available: "/etc/apache2/sites-available"
dest_webapp_dir: "/var/www/webapp"
dest_site_available: "default-ssl.conf"

registry_acr: "acrOnlyMe.azurecr.io"
webappacr: "{{ registry_acr }}/webapp"