---
vm_user: "AzUser"
web_user: "AzUser"
paquetes_requeridos_vm:
  - 'firewalld'
  - 'podman'
  - 'openssl'
  - 'python3-apt'
  - 'python3-passlib'
  - 'httpd'

webcred_user: "operator"
webcred_passwd: ".passwdfile"

ssl_key: "OnlyMe.key"
ssl_cert: "OnlyMe.crt"
ssl_csr: "OnlyMe.csr"
ssl_country_name: "ES"
ssl_org_name: "UNIR"
ssl_org_unit: "DevOpsCloud"
ssl_common_name: "OnlyMe"
ssl_email_address: "borja.rodriguezlopezd077@comunidadunir.net"

root_dir: "/home/{{ web_user }}/webapp"
html_dir: "{{ root_dir }}/html"
basicauth_dir: "{{ root_dir }}/basicauth"
ssl_dir: "{{ root_dir }}/ssl"
conf_dirs:
  - "{{ html_dir }}"
  - "{{ basicauth_dir }}"
  - "{{ ssl_dir }}"
