---
packages_apt:
  - "podman"
  - "openssl"
  - "python3-apt"
  - "python3-passlib"
  - "python3-pip"

packages_pip:
  - "kubernetes>=12.0.0"

vm_user: "AzureUser"
base_conf_dir: "/home/{{ vm_user }}/web_config"
html_dir: "{{ base_conf_dir }}/html"
conf_dirs:
  - "{{ html_dir }}"
