---
- name: Actualizacion apt
  apt:
    update_cache: true
  become: true
  become_user: root
  become_method: sudo

- name: Instalacion de dependencias apt
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ paquetes_requeridos_vm }}"
  become: true
  become_user: root
  become_method: sudo

- name: Creacion de directorios
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ conf_dirs }}"

- name: prueba copia
  copy:
    scr: "/home/ubuntu/Repositorio/casopractico2/ansible/files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"