---
- name: actualizacion apt
  apt:
    update_cache: true
  become: true
  become_user: root
  become_method: sudo

- name: Instalacion de dependencias apt
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages_apt }}"
  become: true
  become_user: root
  become_method: sudo
