---
- name: fw permitir
  become: true
  firewalld:
    port: 8080/tcp
    permanent: true
    immediate: true
    state: enabled

- name: htpasswd basic auth
  become: true
  htpasswd:
    path: "{{ dest_webapp_dir }}/{{ webcred_passwd }}"
    name: "{{ webcred_user }}"
    password: "{{ webcred_pass }}"
    mode: 0644

- name: Copia index
  become: true
  copy:
    src: "index.html"
    dest: "{{ dest_webapp_dir }}"

- name: Copia  de ficheros apache
  become: true
  template:
    src: "default-ssl.conf"
    dest: "{{ dest_sites_available }}"

- name: Habilitar pagina ssl
  become: true
  command: a2ensite default-ssl

- name: Habilitar pagina ssl mod
  become: true
  command: a2enmod ssl