---
- name: fw permitir
  become: true
  firewalld:
    port: 8080/tcp
    permanent: true
    immediate: true
    state: enabled

- name: htpasswd basic auth
  become: true
  htpasswd:
    path: "{{ webapp_dir }}/{{ webcred_passwd }}"
    name: "{{ webcred_user }}"
    password: "{{ webcred_pass }}"
    mode: 0644

- name: Copia index
  become: true
  copy:
    src: "index.html"
    dest: "{{ webapp_dir }}"

- name: Copia  de ficheros apache
  become: true
  copy:
    src: ".htaccess"
    dest: "{{ webapp_dir }}"

- name: Copia  de ficheros apache
  become: true
  copy:
    src: "apache2.conf"
    dest: "{{ webapp_dir }}"
