---
- name: fw permitir
  become: true
  firewalld:
    port: 8080/tcp
    permanent: true
    immediate: true
    state: enabled

- name: htpasswd basic auth
  become: true
  htpasswd:
    path: "{{ basicauth_dir }}/{{ webcred_passwd }}"
    name: "{{ webcred_user }}"
    password: "{{ webcred_pass }}"
    mode: 0644

- name: subir index
  become: true
  copy:
    src: "index.html"
    dest: "{{ html_dir }}"
