---
- name: Desinstalacion de paquetes que no necesitamos
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
          - "{{ packages_prescindibles_apt }}"
  become: true
  become_user: root
  become_method: sudo
