---
- name: 'First'
  hosts: webservers
  remote_user: AzureUser
  become: true
  vars_files:
    - vars/00_vars.yaml
  tasks:
    - name: 'Timezone'
      timezone:
              name: "{{ zone }}"

    - name: 'Actualizar paquetes'
      apt:
        update_cache: yes

    - name: 'Apache'
      apt:
        name: "{{ rpms }}"
        state: present
