---
- name: Gestion Maquina Virtual
  hosts: webservers
  remote_user: "{{ vm_user }}"
  become: true
  vars_files:
    - vars/00_vars.yaml
    - vars/secrets.yaml
  tasks:
    - name: Actualizacion APT y creacion Dirs
      include_tasks: tasks/00_GenWebApp.yaml
    - name: Generacion nginx
      include_tasks: tasks/01_GenNginx.yaml
    - name: Generacion Certificado
      include_tasks: tasks/02_GenSSL.yaml
