---
- name: Gestion Maquina Virtual
  hosts: webservers
  remote_user: "{{ vm_user }}"
  become: true
  vars_files:
    - vars/00_vars.yaml
    - vars/secrets.yaml
  tasks:
    - name: Actualizacion APT y creacion Dirs
      include_tasks: tasks/00_PrepWebApp.yaml
    - name: Generacion apache
      include_tasks: tasks/00_PrepApache.yaml
    - name: Generacion Certificado
      include_tasks: tasks/00_PrepSSL.yaml