---
- name: Logeo en ACR y subida de imagenes
  hosts: webservers
  remote_user: "{{ vm_user }}"
  become: true
  vars_files:
    - vars/00_vars.yaml
    - vars/secrets.yaml
  tasks:
 
    - name: Login acr
      podman_login:
        username: "{{ acruser }}"
        password: "{{ acrpass }}"