---
- name: Gestion Maquina Virtual
  hosts: webservers
  remote_user: "{{ vm_user }}"
  become: true
  vars_files:
    - vars/00_vars.yaml
  tasks:
    - name: Actualizacion APT y creacion Dirs
      include_tasks: tasks/00_tarea.yaml
